services:
  - type: web
    name: url-shortener-frontend
    env: static
    buildCommand: npm install && npx vite build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
