services:
  - type: web
    name: url-shortener-frontend
    env: static
    buildCommand: npm ci && npm run build:prod
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
