services:
  # Frontend (Static Site)
  - type: web
    name: url-shortener-frontend
    env: static
    buildCommand: |
      npm install --force
      npm install @rollup/rollup-linux-x64-gnu --force
      NODE_ENV=production npm run build:vite
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          type: web
          name: url-shortener-backend
          property: host

  # Backend (Web Service)
  - type: web
    name: url-shortener-backend
    env: node
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: url-shortener-backend
          property: port
